language: php
sudo: false

php: ["7", "nightly", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "nightly"}, {"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - secure: "g0uexghpfxjO1pVYCBqj/P957zCZQT1v5naWgzDtu5n2Sh1WoW00K4+jOYJ4bbIm+1O8wbzzlyOuYZMMz0xXLVzuOdoMwMhfcnI+pE/dpa4J/vs1RFqoLh4HuNx9oPErNODdmWIkeC1SpcuBeYZfYxEL6UJIWbZZq3a9BIslx88="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
